// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiFlow.Data;

#nullable disable

namespace ServiFlow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402180928_InicialNueva")]
    partial class InicialNueva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("ServiFlow.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmprendimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ServiFlow.Models.Disponibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmprendimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("ServiFlow.Models.Emprendimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPropio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoServicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Emprendimientos");
                });

            modelBuilder.Entity("ServiFlow.Models.TareaKanban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmprendimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmprendimientoId");

                    b.ToTable("TareasKanban");
                });

            modelBuilder.Entity("ServiFlow.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("ServiFlow.Models.Cita", b =>
                {
                    b.HasOne("ServiFlow.Models.Emprendimiento", "Emprendimiento")
                        .WithMany()
                        .HasForeignKey("EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("ServiFlow.Models.Disponibilidad", b =>
                {
                    b.HasOne("ServiFlow.Models.Emprendimiento", "Emprendimiento")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("ServiFlow.Models.TareaKanban", b =>
                {
                    b.HasOne("ServiFlow.Models.Emprendimiento", "Emprendimiento")
                        .WithMany("TareasKanban")
                        .HasForeignKey("EmprendimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");
                });

            modelBuilder.Entity("ServiFlow.Models.Emprendimiento", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("TareasKanban");
                });
#pragma warning restore 612, 618
        }
    }
}
